name: CI Pipeline

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускать при создании PR в главную ветку

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Flake8
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8

      - name: Run Flake8 linter
        run: |
          source venv/bin/activate
          flake8 --extend-exclude "venv" .

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Black
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install black black[jupyter]

      - name: Run Black formatter
        run: |
          source venv/bin/activate
          black -v --extend-exclude "venv" .

  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies for packaging
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install setuptools build twine

      - name: Build and upload package to PyPI
        run: |
          source venv/bin/activate
          python -m build
          twine upload dist/* -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }} --repository-url https://upload.pypi.org/legacy/

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub (or GitHub Container Registry)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image and push to registry
        run: |
          docker build -t your-docker-image-name .
          docker push your-docker-image-name

  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert Jupyter Notebook to HTML and publish to GitHub Pages
        run: |
          sh script/convert-jupyter-quarto.sh  # скрипт для конвертации.
