name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускать при создании PR в главную ветку

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install jupyter papermill

      - name: Run Jupyter Notebook
        uses: yaananth/run-notebook@v2
        with:
          notebook: "EDA.ipynb"  # Указываем путь к вашему ноутбуку

