name: Run EDA Notebook

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Используйте актуальную версию

      - name: Build Docker image
        run: |
          docker build -t eda-notebook .

      - name: Run Jupyter Notebook
        run: |
          docker run --rm -v "${{ github.workspace }}:/home/jovyan/work" eda-notebook \
          jupyter nbconvert --to notebook --execute EDA.ipynb --output-dir=/home/jovyan/work/plots --output=EDA_output.ipynb
